# Use root/example as user/password credentials

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
    ports:
      - "3307:3307"
    volumes:
      - /Mysql/datadir:/var/lib/mysql
